from typing import Tuple

class CartpoleEnv:
    def __init__(self) -> None: ...
    def step(
        self, action: int
    ) -> Tuple[Tuple[float, float, float, float], float, bool]: ...
    def reset(self) -> Tuple[float, float, float, float]: ...
